config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member  
  end

  resource :cart, only: [:show]
  
  resources :cart_items, only:[:destroy] do
    member do
      patch :plus
      patch :minus
    end
  end

  resources :orders, only: [:create, :index, :destroy] do
    post :checkout_spgateway, on: :member
  end

  resources :order_items

  post 'spgateway/return'
  post 'spgateway/notify'

  namespace :admin do
    resources :products, except: [:show]
    resources :orders, only: [:index, :edit, :update, :destroy]

    root "products#index"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :payments, dependent: :destroy
  
  belongs_to :user

  validates_presence_of :total_amount, :shipping_name, :shipping_phone, :shipping_address
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:update, :destroy]

  def index
    @orders = Order.all.order(created_at: :desc)
  end

  def update
    if @order.update(order_params)
      flash[:notice] = "Successfully updated order ##{@order.sn}"
    else
      flash[:alert] = "Fail to update order. #{@order.errors.full_messages.to_sentence}"
    end

    redirect_to admin_orders_path      
  end

  def destroy
    if @order.payment_status == 'Unpaid'
      if @order.destroy
        flash[:notice] = "Successfully deleted order ##{@order.sn}"
      else
        flash[:alert] = "Fail to delete order. #{@order.errors.full_messages.to_sentence}"
      end
    else
      flash[:alert] = "Can not delete the order which has been paid."
    end

    redirect_to admin_orders_path
  end

  private

  def set_order
    @order = Order.find_by_id(params[:id])
  end

  def order_params
    params.require(:order).permit(:payment_status, :shipping_status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:destroy, :checkout_spgateway]
  skip_before_action :verify_authenticity_token, only: [:checkout_spgateway]

  def create
    if current_cart.cart_items.length == 0
      flash[:alert] = "There is no item in your cart."
      redirect_to root_path
      return
    end

    order = Order.new(order_params)
    order.user = current_user
    order.payment_status = "unpaid"
    order.shipping_status = "not shipped yet"
    order.sn = "0#{rand(10..99)}#{Time.now.strftime("%Y%m%d%H%M%S")}#{current_user.id}".to_i
    order.total_amount = current_cart.calculate_total_amount

    if order.save
      flash[:notice] = "Order has successfully created."
      current_cart.cart_items.each do |cart_item|
        order_item = order.order_items.build(product: cart_item.product, price: cart_item.product.price, quantity: cart_item.quantity)
        order_item.save
      end

      current_cart.destroy
      # UserMailer.notify_order_create(order).deliver_now!

      redirect_to orders_path
    else
      flash[:alert] = "Fail to create order. #{order.errors.full_messages.to_sentence}"

      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def destroy
    if @order.payment_status == 'unpaid'
      if @order.destroy
        flash[:notice] = "Order has been canceled."
      else
        flash[:alert] = "Fail to cancel order. #{@order.errors.full_messages.to_sentence}"
      end
    else
      flash[:alert] = "Can not delete the order which has been paid."
    end
    
    redirect_to orders_path
  end

  def checkout_spgateway
    if @order.payment_status != "unpaid"
      flash[:alert] = "Order has been paid."
      redirect_to orders_path
    else
      @payment = Payment.create!(
        sn: Time.now.to_i,
        order: @order,
        payment_method: params[:payment_method],
        total_amount: @order.total_amount
      )
    end
  end

  private

  def set_order
    @order = Order.find_by_id(params[:id])
  end

  def order_params
    params.require(:order).permit(:shipping_name, :shipping_phone, :shipping_address)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def options_for_payment_status
    [
      ['Unpaid', 'unpaid'],
      ['Paid', 'paid']
    ]
  end

  def options_for_shipping_status
    [
      ['Not shipped yet', 'not shipped yet'],
      ['In delivery', 'in delivery'],
      ['Delivered', 'delivered'],
    ]
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="nav nav-tabs">
      <%= link_to admin_root_path do %>
        <p class="nav-link">Product</p>
      <% end %>
    <li class="nav-item">
      <%= link_to admin_orders_path do %>
        <p class="nav-link active">Orders</p>
      <% end %>
    </li>
  </div>
  <table class="table table-hover">
    <tr>
      <th>Order Number</th>
      <th>Price</th>
      <th>Payment Status</th>
      <th>Shipping Status</th>
      <th></th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.sn %></td>
        <td><%= order.total_amount %></td>
        <td>
          <%= form_for [:admin, order] do |f| %>
            <%= f.select :payment_status, options_for_payment_status %>
            <%= f.submit 'Update', class: "btn btn-primary btn-sm" %>
          <% end %> 
        </td>
        <td>
          <%= form_for [:admin, order] do |f| %>
            <%= f.select :shipping_status, options_for_shipping_status %>
            <%= f.submit 'Update', class: "btn btn-primary btn-sm" %>
          <% end %> 
        </td>
        <td>
          <%= link_to admin_order_path(order), method: :delete, data: {confirm: "Are you sure to delete order ##{order.sn} ?"} do %>
            <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>