config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member  
  end

  resource :cart, only: [:show]
  
  resources :cart_items, only:[:destroy] do
    member do
      patch :plus
      patch :minus
    end
  end

  resources :orders, only: [:create, :index, :destroy] do
    post :checkout_spgateway, on: :member
  end

  resources :order_items

  post 'spgateway/return'
  post 'spgateway/notify'

  namespace :admin do
    resources :products, except: [:show]
    resources :orders, only: [:index, :edit, :update, :destroy]

    root "products#index"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :payments, dependent: :destroy
  
  belongs_to :user

  validates_presence_of :total_amount, :shipping_name, :shipping_phone, :shipping_address
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:update, :destroy]

  def index
    @orders = Order.all.order(created_at: :desc)
  end

  def update
    if @order.update(order_params)
      flash[:notice] = "Successfully updated order ##{@order.sn}"
    else
      flash[:alert] = "Fail to update order. #{@order.errors.full_messages.to_sentence}"
    end

    redirect_to admin_orders_path      
  end

  def destroy
    if @order.payment_status == 'Unpaid'
      if @order.destroy
        flash[:notice] = "Successfully deleted order ##{@order.sn}"
      else
        flash[:alert] = "Fail to delete order. #{@order.errors.full_messages.to_sentence}"
      end
    else
      flash[:alert] = "Can not delete the order which has been paid."
    end

    redirect_to admin_orders_path
  end

  private

  def set_order
    @order = Order.find_by_id(params[:id])
  end

  def order_params
    params.require(:order).permit(:payment_status, :shipping_status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:destroy, :checkout_spgateway]
  skip_before_action :verify_authenticity_token, only: [:checkout_spgateway]

  def create
    if current_cart.cart_items.length == 0
      flash[:alert] = "There is no item in your cart."
      redirect_to root_path
      return
    end

    order = Order.new(order_params)
    order.user = current_user
    order.payment_status = "unpaid"
    order.shipping_status = "not shipped yet"
    order.sn = "0#{rand(10..99)}#{Time.now.strftime("%Y%m%d%H%M%S")}#{current_user.id}".to_i
    order.total_amount = current_cart.calculate_total_amount

    if order.save
      flash[:notice] = "Order has successfully created."
      current_cart.cart_items.each do |cart_item|
        order_item = order.order_items.build(product: cart_item.product, price: cart_item.product.price, quantity: cart_item.quantity)
        order_item.save
      end

      current_cart.destroy
      # UserMailer.notify_order_create(order).deliver_now!

      redirect_to orders_path
    else
      flash[:alert] = "Fail to create order. #{order.errors.full_messages.to_sentence}"

      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def destroy
    if @order.payment_status == 'unpaid'
      if @order.destroy
        flash[:notice] = "Order has been canceled."
      else
        flash[:alert] = "Fail to cancel order. #{@order.errors.full_messages.to_sentence}"
      end
    else
      flash[:alert] = "Can not delete the order which has been paid."
    end
    
    redirect_to orders_path
  end

  def checkout_spgateway
    if @order.payment_status != "unpaid"
      flash[:alert] = "Order has been paid."
      redirect_to orders_path
    else
      @payment = Payment.create!(
        sn: Time.now.to_i,
        order: @order,
        payment_method: params[:payment_method],
        total_amount: @order.total_amount
      )
    end
  end

  private

  def set_order
    @order = Order.find_by_id(params[:id])
  end

  def order_params
    params.require(:order).permit(:shipping_name, :shipping_phone, :shipping_address)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def options_for_payment_status
    [
      ['Unpaid', 'unpaid'],
      ['Paid', 'paid']
    ]
  end

  def options_for_shipping_status
    [
      ['Not shipped yet', 'not shipped yet'],
      ['In delivery', 'in delivery'],
      ['Delivered', 'delivered'],
    ]
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/checkout_spgateway.html.erb
<div class="container">
  <h3 class="text-center">Refering to credit card payment page, please do not close or leave this page...</h3>

  <form name='Spgateway' method='post' action=<%= Spgateway.url %>>
    <% Spgateway.new(@payment).generate_form_data(spgateway_return_url).each do |key, value| %>
      <%= hidden_field_tag key, value %>
    <% end %>
    <input type="submit" value='submit' style="visibility: hidden;">
  </form>  
</div>


<script>
  document.forms[0].submit();
</script>

app/views/orders/index.html.erb
<div class="container">
  <% if @orders.length != 0 %>
    <% @orders.each do |order| %>
      <div class="card order-card">
        <div class="card-header">
          <h6>Order #<%= order.sn %></h6>
        </div>
        <div class="card-body">
          <div class="product-area">
            <table class="table">
              <% order.order_items.each do |order_item| %>
                <tr>
                  <td><%= order_item.product.name %></td>
                  <td><%= order_item.quantity %></td>
                  <td>$<%= order_item.calculate_subtotal %></td>
                </tr>
              <% end %>
              <tr>
                <td>Total Amount:</td>
                <td></td>
                <td>$<%= order.total_amount %></td>
              </tr>
            </table>
          </div>
          <div class="shipping-area">
            <div class="card">
              <div class="card-header">
                <h6>Shipping Information</h6>
              </div>
              <div class="card-body">
                <p>Shipping Name: <%= order.shipping_name %></p>
                <p>Shipping Phone: <%= order.shipping_phone %></p>
                <p>Shipping Address: <%= order.shipping_address %></p>
              </div>
            </div>
          </div>
          <div class="status-area">
            <h5>Payment Status: <%= order.payment_status %></h5>
            <h5>Shipping Status: <%= order.shipping_status %></h5>
            <% if order.payment_status == 'unpaid' %>
              <% Payment::PAYMENT_METHODS.each do |method| %>
                <%= link_to checkout_spgateway_order_path(order, payment_method: method), method: :post do %>
                  <button class="btn btn-primary"><%= method %></button>
                <% end %>
              <% end %> 
            <% end %>
            <%= link_to order_path(order), method: :delete, data: {confirm: "Are you sure to delete Order ##{order.sn} ?"} do %>
              <button class="btn btn-outline-danger">Cancel Order</button>
            <% end %>   
          </div>
        </div>
      </div>   
    <% end %>
  <% else %>
  <div class="text-center">
    <em>There is no order.</em>
  </div>
  <% end %>
</div>