config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member  
  end

  resource :cart, only: [:show]
  
  resources :cart_items, only:[:destroy] do
    member do
      patch :plus
      patch :minus
    end
  end

  resources :orders, only: [:create, :index, :destroy] do
    post :checkout_spgateway, on: :member
  end

  resources :order_items

  post 'spgateway/return'
  post 'spgateway/notify'

  namespace :admin do
    resources :products, except: [:show]
    resources :orders, only: [:index, :edit, :update, :destroy]

    root "products#index"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  
  has_many :order_items

  validates_presence_of :name, :price, :description

  mount_uploader :image, PhotoUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:edit, :update, :destroy, :add_to_cart]

  helper_method :current_cart

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Product was successfully created."
    else
      flash[:notice] = "Product was failed to creat. #{@product.errors.full_messages.to_sentence}"
    end

    redirect_to admin_root_path
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = "Have successfully updated the product."
    else 
      flash[:alert] = "Fail to update the product. #{@product.errors.full_messages.to_sentence}"
    end

    redirect_to admin_root_path
  end

  def destroy
    @product.destroy

    redirec_to admin_root_path, notice: "Product has successfully deleted"
  end

  private

  def set_product
    @product = Product.find_by_id(params[:id])  
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def add_to_cart
    @product = Product.find_by_id(params[:id])

    current_cart.add_cart_item(@product)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<%= render partial: "admin/shared/form", locals: { product: @product } %>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="nav nav-tabs">
      <%= link_to admin_root_path do %>
        <p class="nav-link active">Product</p>
      <% end %>
    <li class="nav-item">
      <%= link_to admin_orders_path do %>
        <p class="nav-link">Orders</p>
      <% end %>
    </li>
  </div>
  <%= link_to new_admin_product_path do %>
    <button class="btn btn-primary">New Product</button>
  <% end %> 
  <table class="table table-hover">
    <tr class="text-center">
      <th>Product Name</th>
      <th>Image</th>
      <th>Price</th>
      <th>Option</th>
    </tr>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td>
          <% if product.image_remote_url? %>
            <%= image_tag(product.image_remote_url, style: "width: 100px; height: 100px; margin: 0 auto;") %>
          <% elsif product.image? %>
            <%= image_tag(product.image, style: "width: 100px; height: 100px; margin: 0 auto;") %>
          <% end %>
        </td>
        <td class="text-center">$<%= product.price %></td>
        <td class="text-center">
          <%= link_to edit_admin_product_path(product) do %>
            <button class="btn btn-primary"><i class="fa fa-edit"></i></button>
          <% end %>
          <%= link_to admin_product_path(product), method: :delete do %>
            <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/products/new.html.erb
<%= render partial: "admin/shared/form", locals: { product: @product } %>