config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member  
  end

  resource :cart, only: [:show]
  
  resources :cart_items, only:[:destroy] do
    member do
      patch :plus
      patch :minus
    end
  end

  resources :orders, only: [:create, :index, :destroy] do
    post :checkout_spgateway, on: :member
  end

  resources :order_items

  post 'spgateway/return'
  post 'spgateway/notify'

  namespace :admin do
    resources :products, except: [:show]
    resources :orders, only: [:index, :edit, :update, :destroy]

    root "products#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy

  def add_cart_item(product)
    existing_item = self.cart_items.find_by( product: product )
    if existing_item
      existing_item.quantity += 1
      existing_item.save!
    else
      cart_item = cart_items.build( product: product )
      cart_item.save!
    end
    self.cart_items
  end

  def calculate_total_amount
    @total_amount = 0
    self.cart_items.each do |cart_item|
      @total_amount += cart_item.product.price * cart_item.quantity  
    end
    @total_amount
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  default_scope { order(created_at: :asc) }

  def calculate_subtotal
    self.product.price * self.quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :payments, dependent: :destroy
  
  belongs_to :user

  validates_presence_of :total_amount, :shipping_name, :shipping_phone, :shipping_address
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def calculate_subtotal
    self.price * self.quantity
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order

  PAYMENT_METHODS = %w(Credit WebATM ATM)
  validates_inclusion_of :payment_method, in: PAYMENT_METHODS

  after_update :update_order_status

  def deadline
    Date.today + 3.days
  end

  def self.find_and_process(params)
    trade_info = params['TradeInfo']
    trade_sha = params['TradeSha']

    data = Spgateway.decrypt(trade_info, trade_sha)
   
    # 根據參數的 MerchantOrderNo，查出 payment 實例
    # 更新相關的 payment 與 order 屬性

    if data
      payment = Payment.find(data['Result']['MerchantOrderNo'].to_i)
      if params['Status'] == 'SUCCESS'
        payment.paid_at = Time.now
      end
      payment.params = data

      return payment
    else
      return nil
    end    
  end

  def update_order_status
    if self.paid_at
      order = self.order
      order.update(payment_status: 'paid')
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  
  has_many :order_items

  validates_presence_of :name, :price, :description

  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders, dependent: :destroy


  def is_admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart 
  helper_method :calculate_cart_total_quantity

  private

  def current_cart
    @cart || set_cart
  end

  def set_cart
    if session[:cart_id]
      @cart = Cart.find_by_id(session[:cart_id])
    end

    @cart ||= Cart.create

    session[:cart_id] = @cart.id
    @cart
  end

  def calculate_cart_total_quantity(cart_items)
    totoal_quantity = 0
    cart_items.each do |cart_item|
      totoal_quantity += cart_item.quantity
    end

    totoal_quantity
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item

  def destroy
    @cart_item.destroy

    render "products/add_to_cart"
  end

  def plus
    quantity = @cart_item.quantity + 1

    @cart_item.update_attributes(quantity: quantity)    

    render "products/add_to_cart"
  end

  def minus
    quantity = @cart_item.quantity - 1

    @cart_item.update_attributes(quantity: quantity)

    render "products/add_to_cart" 
  end

  private

  def set_cart_item
    @cart_item = CartItem.find_by_id(params[:id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
     @order = Order.new 
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:destroy, :checkout_spgateway]
  skip_before_action :verify_authenticity_token, only: [:checkout_spgateway]

  def create
    if current_cart.cart_items.length == 0
      flash[:alert] = "There is no item in your cart."
      redirect_to root_path
      return
    end

    order = Order.new(order_params)
    order.user = current_user
    order.payment_status = "unpaid"
    order.shipping_status = "not shipped yet"
    order.sn = "0#{rand(10..99)}#{Time.now.strftime("%Y%m%d%H%M%S")}#{current_user.id}".to_i
    order.total_amount = current_cart.calculate_total_amount

    if order.save
      flash[:notice] = "Order has successfully created."
      current_cart.cart_items.each do |cart_item|
        order_item = order.order_items.build(product: cart_item.product, price: cart_item.product.price, quantity: cart_item.quantity)
        order_item.save
      end

      current_cart.destroy
      # UserMailer.notify_order_create(order).deliver_now!

      redirect_to orders_path
    else
      flash[:alert] = "Fail to create order. #{order.errors.full_messages.to_sentence}"

      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def destroy
    if @order.payment_status == 'unpaid'
      if @order.destroy
        flash[:notice] = "Order has been canceled."
      else
        flash[:alert] = "Fail to cancel order. #{@order.errors.full_messages.to_sentence}"
      end
    else
      flash[:alert] = "Can not delete the order which has been paid."
    end
    
    redirect_to orders_path
  end

  def checkout_spgateway
    if @order.payment_status != "unpaid"
      flash[:alert] = "Order has been paid."
      redirect_to orders_path
    else
      @payment = Payment.create!(
        sn: Time.now.to_i,
        order: @order,
        payment_method: params[:payment_method],
        total_amount: @order.total_amount
      )
    end
  end

  private

  def set_order
    @order = Order.find_by_id(params[:id])
  end

  def order_params
    params.require(:order).permit(:shipping_name, :shipping_phone, :shipping_address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def add_to_cart
    @product = Product.find_by_id(params[:id])

    current_cart.add_cart_item(@product)
  end
end

app/controllers/spgateway_controller.rb
class SpgatewayController < ApplicationController
  skip_before_action :verify_authenticity_token

  def return
    payment = Payment.find_and_process(spgateway_params)

    if payment&.save
      flash[:notice] = "#{payment.order.sn} paid"
    else
      flash[:alert] = "Somethint went wrong. Please try again later."
    end

    redirect_to orders_path
  end

  def notice
    payment = Payment.find_and_process(spgateway_params)
    
    if payment&.save
      render text: "1|OK"
    else
      render text: "0|ErrorMessage"
    end
  end

  def spgateway_params
    params.slice("Status", "MerchantID", "Version", "TradeInfo", "TradeSha")
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/shared/_form.html.erb
<div class="container">
  <%= form_for [:admin, product] do |f| %>
    <%= f.label 'Product Name' %>
    <%= f.text_field :name, maxlength: 30, class: "form-control" %>
    <%= f.label 'Description' %>
    <%= f.text_area :description, maxlength: 140, class: "form-control" %>
    <%= f.label 'Price'%>
    <%= f.number_field :price, step: :any, class: "form-control" %>
    <%= image_tag(product.image, width: '300px') if product.image? %>
    <%= f.file_field :image %>
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to admin_root_path do %>
      <button class="btn btn-danger">Cancel</button>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CartMoney</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>
  <body>
    <header>
      <nav>
        <div class="container">
          <div class="logo"><%= link_to 'West World Shop', root_path %></div>
          <div class="menu">
            <% if current_user %>
              <% if current_user.role == 'admin' %>
                <div><%= link_to 'Admin panel', admin_root_path %></div>
              <% end %>
            <% end %>
            <div class="cart-btn">Cart <%= "( #{calculate_cart_total_quantity(current_cart.cart_items)} )" if current_cart.cart_items.length != 0 %></div>
            <div><%= link_to 'Order', orders_path %></div>
            <% if current_user %>
              <div><%= link_to 'Logout', destroy_user_session_path, method: :delete %></div>
            <% else %>
              <div><%= link_to('Sign up', new_user_registration_path ) %></div>
              <div><%= link_to('Sign in', new_user_session_path ) %></div>
            <% end %>
          </div>      
        </div>
      </nav>  
    </header>
    <div class="alert-row">
      <% if flash[:notice] %>
        <div class="notice alert alert-success" role="alert">
          <div class="container">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
            <div class="text-center">
              <%= flash[:notice] %>
            </div>
          </div>
        </div>
      <% elsif flash[:alert]%> 
        <div class="alert alert-danger" role="alert">
          <div class="container">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
            <div class="text-center">
              <%= flash[:alert] %>
            </div>
          </div>
        </div>               
      <% end %>
    </div>
    <div class="cart-panel shadow-box">
      <%= render partial: "shared/cart" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_cart.html.erb
<h3>Cart</h3>
<div class="close-btn"><i class="fa fa-times"></i></div>
<hr />
<% if current_cart.cart_items.length != 0 %>
  <% current_cart.cart_items.each do |cart_item| %>
    <div id="cart-item-<%= cart_item.id %>" class="cart-item">
      <div class="cart-item-top">
        <div class="cart-item-img">
          <% if cart_item.product.image_remote_url? %>
            <%= image_tag(cart_item.product.image_remote_url) %>
          <% elsif cart_item.product.image? %>
            <%= image_tag(cart_item.product.image) %>
          <% end %>
        </div>
        <div class="cart-item-info">
          <h6><%= cart_item.product.name %></h6>
          <h6>$<%= cart_item.product.price.round %></h6>
        </div>
      </div>
      <div class="cart-item-bottom">
        <div>
          <%= link_to plus_cart_item_path(cart_item), method: :patch, remote: true do %>
            <button class="btn btn-sm btn-warning"><i class="fa fa-plus"></i></button>
          <% end %> 
        </div>
        <h5 class="text-center"><%= cart_item.quantity %></h5>
        <% if cart_item.quantity == 1 %>
          <button class="btn btn-sm btn-warning" disabled><i class="fa fa-minus"></i></button>
        <% else %>
          <div>
            <%= link_to minus_cart_item_path(cart_item), method: :patch, remote: true do %>
              <button class="btn btn-sm btn-warning"><i class="fa fa-minus"></i></button>
            <% end %> 
          </div>
        <% end %>
        <div class="trash-btn">
          <%= link_to cart_item_path(cart_item), method: :delete, remote: true, data: {confirm: "Are you sure to delete #{cart_item.product.name} from cart?"} do %>
            <button class="btn btn-sm"><i class="fa fa-trash"></i></button>
          <% end %> 
        </div>
      </div>
    </div>
  <% end %>
  <hr />
  <div>
    <h5>Total Amount:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$<%= current_cart.calculate_total_amount %></h5>
  </div>
  <div class="cart-details-btn">
    <%= link_to cart_path do %>
      <button class="btn btn-primary">View Cart Details</button>
    <% end %>
  </div>
<% else %>
  <em>There is nothing in your cart.</em>
<% end %>

app/views/shared/_cart_table.html.erb
<table class="table table-hover cart-table">
  <tr>
    <th></th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th></th>
  </tr>
  <% current_cart.cart_items.each do |cart_item| %>
    <tr>
      <td class="cart-table-img-name">
        <div class="cart-table-img">          
          <% if cart_item.product.image_remote_url? %>
            <%= image_tag(cart_item.product.image_remote_url) %>
          <% elsif cart_item.product.image? %>
            <%= image_tag(cart_item.product.image) %>
          <% end %>
        </div>
        <div><h6><%= cart_item.product.name %><h6></div>
      </td>
      <td><h6>$<%= cart_item.product.price %></h6></td>
      <td>
        <div class="cart-item-bottom">
          <div>
            <%= link_to plus_cart_item_path(cart_item), method: :patch, remote: true do %>
              <button class="btn btn-sm btn-warning"><i class="fa fa-plus"></i></button>
            <% end %> 
          </div>
          <h6 class="text-center"><%= cart_item.quantity %></h6>
          <% if cart_item.quantity == 1 %>
            <button class="btn btn-sm btn-warning" disabled><i class="fa fa-minus"></i></button>
          <% else %>
            <div>
              <%= link_to minus_cart_item_path(cart_item), method: :patch, remote: true do %>
                <button class="btn btn-sm btn-warning"><i class="fa fa-minus"></i></button>
              <% end %> 
            </div>
          <% end %>
        </div>              
      </td>
      <td><h6>$<%= cart_item.calculate_subtotal %></h6></td>
      <td>
        <%= link_to cart_item_path(cart_item), method: :delete, remote: true, data: {confirm: "Are you sure to delete #{cart_item.product.name} from cart?"} do %>
          <button class="btn btn-sm"><i class="fa fa-trash"></i></button>
        <% end %> 
      </td>
    </tr>
  <% end %>
  <tr>
    <td></td>
    <td><h5>Total Amount:<h5></td>
    <td></td>
    <td><h5>$<%= current_cart.calculate_total_amount %></h5></td>
    <td></td>
  </tr>
</table>